FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:jessie

RUN install_packages curl bzip2 xclip mesa-utils mtdev-tools crudini

ENV APP_VER 1.16.3
RUN curl --silent \
	https://autosportlabs-software.s3-us-west-2.amazonaws.com/racecapture_linux_raspberrypi__${APP_VER}.tar.bz2 | \
	tar xj

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

WORKDIR /app
ENTRYPOINT [ "/app/entrypoint.sh" ]
CMD [ "/racecapture/racecapture" ]
